# Generated by Django 5.1.3 on 2025-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peleadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=100)),
            ],
        ),
    ]
