# Generated by Django 5.1.3 on 2025-01-17 09:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_ufc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('usuario', models.ManyToManyField(related_name='Usuarios_comentarios', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Noticias', to='ufc.noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Pelea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('asaltos', models.IntegerField()),
                ('categoria', models.ForeignKey(default='pendiente', on_delete=django.db.models.deletion.CASCADE, related_name='Pelea', to='ufc.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('peleas', models.ManyToManyField(blank=True, related_name='Evento_peleas', to='ufc.pelea')),
            ],
        ),
        migrations.CreateModel(
            name='Peleadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('posicion', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=100)),
                ('categoria', models.ManyToManyField(related_name='Peleadores', to='ufc.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pelea',
            name='ganador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ganador', to='ufc.peleadores'),
        ),
        migrations.AddField(
            model_name='pelea',
            name='peleador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Peleador_1', to='ufc.peleadores'),
        ),
        migrations.AddField(
            model_name='pelea',
            name='peleador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Peleador_2', to='ufc.peleadores'),
        ),
        migrations.AddField(
            model_name='pelea',
            name='perdedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Perdedor', to='ufc.peleadores'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='peleadores',
            field=models.ManyToManyField(blank=True, default='pendiente', related_name='Categoria_peleadores', to='ufc.peleadores'),
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField()),
                ('empate', models.BooleanField(blank=True, default=False)),
                ('KO', models.BooleanField(blank=True, default=False)),
                ('asalto', models.IntegerField(blank=True)),
                ('fecha', models.DateField()),
                ('usuario', models.ManyToManyField(related_name='Usuarios_apuestas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='ufc.evento')),
                ('pelea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pelea', to='ufc.pelea')),
                ('ganador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Apuesta_Ganador', to='ufc.peleadores')),
            ],
        ),
    ]
