# Generated by Django 5.1.3 on 2025-01-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100000)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='peleadores',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='peleadores',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('peleadores', models.ManyToManyField(related_name='Peleadores_categoria', to='ufc.peleadores')),
            ],
        ),
        migrations.CreateModel(
            name='Pelea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('asaltos', models.IntegerField()),
                ('ganador', models.CharField(max_length=100)),
                ('perdedor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('peleador1', models.ManyToManyField(related_name='Peleador_1', to='ufc.peleadores')),
                ('peleador2', models.ManyToManyField(related_name='Peleador_2', to='ufc.peleadores')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('peleas', models.ManyToManyField(to='ufc.pelea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Noticias', to='ufc.noticias')),
                ('usuario', models.ManyToManyField(related_name='Usuarios_comentarios', to='ufc.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField()),
                ('ganador', models.CharField(blank=True, max_length=100)),
                ('empate', models.BooleanField(blank=True, default=False)),
                ('KO', models.BooleanField(blank=True, default=False)),
                ('asalto', models.IntegerField(blank=True)),
                ('fecha', models.DateField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='ufc.evento')),
                ('pelea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pelea', to='ufc.pelea')),
                ('usuario', models.ManyToManyField(related_name='Usuarios_apuestas', to='ufc.usuarios')),
            ],
        ),
    ]
